/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.workapi.samples.java;

import com.workapi.model.User;
import com.workapi.model.Integration;
import com.workapi.client.rest.WorkApiClient;
import java.io.Console;

public class App {
  private WorkApiClient client;
  private WorkApiClient getClient() {
    if (this.client == null) { 
      String token = "**** YOUR TOKEN GOES HERE ****";
      this.client = new WorkApiClient(token);
    }
    return this.client; 
  }

  public static void main(String[] args) {
    new App().run();
  }

  public void run() {
    WorkApiClient client = getClient();

    User user = client.users.fetch();
    System.out.println("Connected to WorkAPI"); 
    System.out.println("User ID: " + user.getArbitraryId()); 

    Integration newIntegration = new Integration("gmail", null, "email");
    Integration createdIntegration = client.integrations.create(newIntegration);
    System.out.println("Created Integration: " + createdIntegration.getId());

    String authURL = client.integrations.auth(createdIntegration.getId());
    System.out.println("Visit the following URL to authorize the created integration");
    System.out.println(authURL);
  }
}
